name = "backend"
compatibility_date = "2023-12-01"

[vars]
JWT_SECRET = "mysupersecretpassword"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzdkZTVjYmMtOWM2OC00ZThlLTg3ZmQtZDJiZTI5YjQyOWIwIiwidGVuYW50X2lkIjoiMDU1MmE3YzZjZWE2YjJlNmFlYjk5M2E2ZmU3YmMxMTdmYzg0ODRlZGVjNjlkMzg4ZGNiOGRmMjVkMDJlMjRjYyIsImludGVybmFsX3NlY3JldCI6IjZmMDExN2Y1LWRjNmYtNDhhOC1iYzkyLWRiMTA0ZjM2MTNjZiJ9.u4Lpf5Fd24urkn_re4eeR9YuWb07-fnNG1MlQXfKI_U"
# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"